# Bind Configurations
cp /etc/named.conf ~/named.conf-14040510
#
vim /etc/named.conf
	options {
        listen-on port 53 { 192.168.56.102; };
        listen-on-v6 port 53 { none; };
        directory       "/var/named";
        dump-file       "/var/named/data/cache_dump.db";
        statistics-file "/var/named/data/named_stats.txt";
        memstatistics-file "/var/named/data/named_mem_stats.txt";
        secroots-file   "/var/named/data/named.secroots";
        recursing-file  "/var/named/data/named.recursing";
        allow-query     { any; };

	recursion no;
	dnssec-validation no;

# Add The End Of File
zone "mcloud.local" {
        type master;
        file "/etc/named/zones/db.mcloud.local";
};
